name: Build and push

on:
  push:
  
  schedule:
    - cron:  '0 2 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone web
      run: git clone https://github.com/standardnotes/web.git

    - name: Applying patch
      run: cp production.patch ./web && cd web && git apply ./production.patch

    - name: Build the Docker image
      run: docker build -t chrisnharvey/standardnotes-web:latest .

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        email: ${{ secrets.DOCKER_EMAIL }}
        
    - name: Push image to registry
      run: docker push chrisnharvey/standardnotes-web:latest
